[program:hardhat-viem]
process_name=%(program_name)s
user=debian
directory=/home/debian/panel/supervisor/services/hardhat-viem
command=/home/debian/.nvm/versions/node/v24.16.0/bin/npx hardhat node
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/home/debian/panel/storage/logs/supervisor/hardhat-viem.log
stopwaitsecs=3600