[program:laravel-pulse]
process_name=%(program_name)s
user=debian
directory=/home/debian/panel
command=php artisan pulse:check
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/home/debian/panel/storage/logs/supervisor/pulse.log
stopwaitsecs=3600