[program:laravel-octane]
process_name=%(program_name)s
user=debian
directory=/home/debian/panel
command=php artisan octane:start --workers=4 --task-workers=6 --max-requests=250 --server=swoole --host=0.0.0.0 --port=8000
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/home/debian/panel/storage/logs/supervisor/octane.log
stopwaitsecs=3600