[program:laravel-reverb]
process_name=%(program_name)s
user=debian
directory=/home/debian/panel
command=php artisan reverb:start
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/home/debian/panel/storage/logs/supervisor/reverb.log
stopwaitsecs=3600