[program:laravel-queue]
process_name=%(program_name)s
user=debian
directory=/home/debian/panel
command=php artisan queue:work
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/home/debian/panel/storage/logs/supervisor/queue.log
stopwaitsecs=3600