[program:laravel-horizon]
process_name=%(program_name)s
user=debian
directory=/home/debian/panel
command=php artisan horizon
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/home/debian/panel/storage/logs/supervisor/horizon.log
stopwaitsecs=3600