[program:laravel-schedule]
process_name=%(program_name)s
user=debian
directory=/home/debian/panel
command=php artisan schedule:work
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/home/debian/panel/storage/logs/supervisor/schedule.log
stopwaitsecs=3600